version: "3.5"
services:
    dojo-php:
        build:
            context: .
        image: nanoninja/php-fpm:7.4.4
        container_name: dojo-php
        volumes:
            - .:/var/www/html
        command: ["./docker-entrypoint.sh"]
